name: Bug Report
description: Something isn't working like it's supposed to
title: "[Bug]: "
labels: ["bug"]
assignees:
  - MillironX
body:
  - type: markdown
    attributes:
      value: |
        > _Thanks for helping squash bugs in HapLink!_ :smile:
        > _This template is rather extensive._
        > _Please fill out all that you can, but remember that this template_
        > _is only a tool: if you feel that anything is not relavant, simply_
        > _leave it blank._
  - type: markdown
    attributes:
      value: |
        ## Behavior
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what you expected to happen
      placeholder: "It should just work!"
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Tell us what actually happened
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce

        **Make sure to fill in at least one of the following!**

  - type: textarea
    id: stepfiles
    attributes:
      label: File(s) that cause bug
      description: |
        Please drag and drop (i.e. upload to the GitHub issue) the exact files
        that are causing the problem. If needed, you can zip/tarball them
        first.
      placeholder: |
        - [sample.bam](#)
        - [reference.fasta](#)
  - type: textarea
    id: stepshell
    attributes:
      label: Shell command that causes bug
      description: |
        Enter the command(s) used to produce the bug on the command line
        without command output
      placeholder: |
        haplink sample.bam -r reference.fasta
      render: shell
  - type: textarea
    id: steprepl
    attributes:
      label: REPL command that causes bug
      description: |
        Enter the Julia code used to produce the bug in the REPL without prompt
        or output
      placeholder: |
        using HapLink
        callvariants(kwargs...)
  - type: markdown
    attributes:
      value: |
        ## More Info
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Tell us what you are trying to accomplish and/or how this bug affects
        users in the "real world."
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        **(Highly optional, but highly useful.)**
        If you can figure out a design decision or a particular function call
        that is causing the bug, explain here.
        Even better, if you know a way to fix it, but don't want to open a pull
        request, then explain the fix here.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    attributes:
      label: OS and version
      placeholder: "Fedora 34"
  - type: input
    attributes:
      label: Julia version
      placeholder: "1.6.4"
  - type: input
    attributes:
      label: Julia install method
      placeholder: "Fedora repos"
  - type: input
    attributes:
      label: bam-readcount version
      placeholder: "1.0.0"
  - type: input
    attributes:
      label: bam-readcount install method
      placeholder: "built from source"
  - type: input
    attributes:
      label: HapLink version
      placeholder: "0.0.1"
  - type: checkboxes
    attributes:
      label: HapLink usage method(s)
      options:
        - label: Command line
        - label: Julia REPL
