name: Binary Builder
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  binary_build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia -e 'using Pkg; Pkg.add("PackageCompiler")'
      - run: |
          julia -e '
          using PackageCompiler
          create_app(
            ".",
            "build",
            precompile_execution_file="precompile_app.jl",
            executables=[
              "haplink" => "haplink",
            ],
            cpu_target="x86-64"
          )'
      - env:
          TAG: ${{ github.ref }}
        run: |
          tar cv -C build . | gzip -9 > HapLink-${TAG}_linux.x86_64.tar.gz
      - uses: ffurrer2/extract-release-notes@v1
        id: news
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: HapLink-*_{linux,mac,win}.x86_64.{tar.gz,zip}
          body: |
            ${{ steps.news.outputs.release_notes }}

  docker_build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - id: get-version
        run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION/v/}
          echo "::set-output name=VERSION::$VERSION"
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            quay.io/millironx/haplink:${{ steps.get-version.outputs.VERSION }}
            quay.io/millironx/haplink:latest
