name: Binary Builder
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  binary_build:
    name: Build Binaries
    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - id: tag_name
        shell: bash
        run: |
          echo ::set-output name-SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia -e 'using Pkg; Pkg.add("PackageCompiler")'
        shell: bash
      - run: |
          julia -e '
          using PackageCompiler
          create_app(
            ".",
            "build",
            executables=[
              "haplink" => "haplink",
              "make-haplotype-fastas" => "make_haplotype_fastas"
            ],
            cpu_target="x86-64"
          )'
        shell: bash
      - if: ${{ matrix.config.os == 'ubuntu-latest' }}
        shell: bash
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          tar cv build/* | gzip -9 > HapLink-${SOURCE_TAG}_linux.x86_64.tar.gz
      - if: ${{ matrix.config.os == 'macos-latest' }}
        shell: bash
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          tar cv build/* | gzip -9 > HapLink-${SOURCE_TAG}_mac.x86_64.tar.gz
      - if: ${{ matrix.config.os == 'windows-latest' }}
        shell: pwsh
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          Compress-Archive -Path .\build\* -DestinationPath .\HapLink-${SOURCE_TAG}_win.x86_64.zip
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: HapLink-*_{linux,mac,win}.x86_64.{tar.gz,zip}
